### PR TITLE
📑 :: Change class 생성 / Admin UI class 수정

### LINKED ISSUE #46: Change class 생성

### PR DESCRIPTION
**Pull request by goodchoi**
close #46

### CODE REVIEW

**Review by Neetjun — APPROVED** [review]
Amazing Beautiful
LGTM

**Review by Neetjun — APPROVED** [review]
LGTM

**Review by 2kkeullim — APPROVED** [review]
LGTM

**Review by buuuk1 — APPROVED** [review]
LGTM

**Review by egw001 — APPROVED** [review]

**Pull request merged**
